[tool.poetry]
name = "flockwave-server"
version = "2.10.3"
description = "Skybrush server component"
authors = ["Tamas Nepusz <tamas@collmot.com>", "Gabor Vasarhelyi <vasarhelyi@collmot.com>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "flockwave", from = "src" },
    { include = "skybrush", from = "src" }
]


[[tool.poetry.source]]
name = "fury"
url = "https://pypi.fury.io/skybrush/"
secondary = true

[tool.poetry.dependencies]
python = "^3.8"
bidict = ">=0.19.0"
click = "^8.0.0"
blinker = "^1.4"
jsonschema = "^4.0.3"
python-baseconv = "^1.2.2"
pynmea2 = "^1.15.0"
trio = "0.21.0"
quart = ">=0.18.0"
quart-trio = ">=0.10.0"
trio-util = ">=0.5.0"
python-dotenv = ">=0.14.0"
colour = ">=0.1.5"
pyjwt = "^1.7.1"
hypercorn = {extras = ["trio"], version = ">=0.10.1"}
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
flockwave-app-framework = {version = "^2.6.0", extras = ["daemon"], source = "fury"}
flockwave-async = {version = "^1.3.0", source = "fury"}
flockwave-conn = {extras = ["rpc", "serial"], source = "fury", version = "^6.1.0"}
flockwave-ext = {version = "^1.19.2", source = "fury"}
flockwave-gps = {version = "2.2.0", source = "fury"}
flockwave-logger = {version = "^1.8.0", source = "fury"}
flockwave-mavlink = {version = ">=0.1.0", source = "fury"}
flockwave-net = {extras = ["async"], version = "^4.0.1", source = "fury"}
flockwave-parsers = {version = "^2.0.1", source = "fury"}
flockwave-spec = {path = "../flockwave-spec"}

pymongo = ">=4.0.0"
pydantic = "<2.0.0"
soundfile = ">=0.12.0"
sounddevice = ">=0.4.3"
pyudev = ">=0.22.0"
couchdb = ">=1.2.0"
elevenlabs = "^0.2.0"
pygame = "^2.3.0"
matplotlib = "^3.7.0"
shapely = "^2.0.0"
openai = "^0.27.0"
scipy = "^1.1.0"
pyledctrl = {version = "^4.0.1", source = "fury"}
aiocflib = "^2.6.0"
appdirs = "^1.4.4"
crcmod = "^1.7"
msgpack = "^1.0.0"
aio-usb-hotplug = "^5.2.0"
pyserial = "^3.4"
compose = "^1.1.1"
adrenaline = "^1.1.0"
httpx = ">=0.18.2"
igrf-model = "^1.1.1"
skybrush-ext-controller-poc = {path = "../skybrush-ext-controller-poc"}
skybrush-ext-rl-gaming = {path = "../skybridge-ext-rl-gaming"}
boto3 = "^1.26.147"



[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^7.1.0"}
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-trio = ">=0.6.0"
pdoc = "^12.3.0"

[tool.poetry.extras]
all = ["skybrush-ext-dock", "skybrush-ext-flockctrl", "skybrush-ext-map-cache", "skybrush-ext-sidekick", "skybrush-ext-timecode"]
collmot = ["skybrush-ext-dock", "skybrush-ext-flockctrl", "skybrush-ext-map-cache", "skybrush-ext-timecode"]
pro = ["skybrush-ext-map-cache", "skybrush-ext-sidekick", "skybrush-ext-timecode"]

[tool.poetry.scripts]
skybrushd = "flockwave.server.launcher:start"
skybrush-gateway = "flockwave.gateway.launcher:start"
skybrush-proxy = "flockwave.proxy.launcher:start"
